# Generated by Django 5.2.5 on 2025-08-11 19:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_booking_options_alter_car_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='العلامة التجارية'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'بنزين'), ('diesel', 'ديزل'), ('electric', 'كهرباء'), ('hybrid', 'هجين')], default='gasoline', max_length=20, verbose_name='نوع الوقود'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='cars/default_car.jpg', upload_to='cars/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاح'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=255, verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر اليومي'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(default=5, verbose_name='عدد المقاعد'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'أوتوماتيك'), ('manual', 'يدوي')], default='automatic', max_length=20, verbose_name='ناقل الحركة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(verbose_name='السنة'),
        ),
    ]
